"""
Curated skill and job-role lists for search/tag autocomplete (common across industries).
Sourced from typical ATS keyword lists and O*NET-style role families (condensed).
"""

SKILL_SUGGESTIONS = sorted(
    {
        # Programming & frameworks
        "Python",
        "JavaScript",
        "TypeScript",
        "Java",
        "C#",
        "C++",
        "Go",
        "Rust",
        "Ruby",
        "PHP",
        "Swift",
        "Kotlin",
        "R",
        "SQL",
        "NoSQL",
        "HTML",
        "CSS",
        "React",
        "Angular",
        "Vue.js",
        "Node.js",
        "Django",
        "Flask",
        "FastAPI",
        "Spring Boot",
        ".NET",
        "REST API",
        "GraphQL",
        "Microservices",
        "System design",
        # Data & analytics
        "Data analysis",
        "Data visualization",
        "Statistics",
        "Excel",
        "Power BI",
        "Tableau",
        "Pandas",
        "NumPy",
        "ETL",
        "Snowflake",
        "Databricks",
        "Apache Spark",
        "Machine learning",
        "Deep learning",
        "NLP",
        "Computer vision",
        "TensorFlow",
        "PyTorch",
        "A/B testing",
        # Cloud & DevOps
        "AWS",
        "Azure",
        "GCP",
        "Docker",
        "Kubernetes",
        "Terraform",
        "CI/CD",
        "Jenkins",
        "GitHub Actions",
        "Linux",
        "Bash",
        "Networking",
        "Security",
        "IAM",
        # Product & design
        "Product management",
        "Roadmapping",
        "User research",
        "UI/UX",
        "Figma",
        "Wireframing",
        "Agile",
        "Scrum",
        "Jira",
        "Confluence",
        # Business & ops
        "Project management",
        "Stakeholder management",
        "Budgeting",
        "Process improvement",
        "Operations",
        "Supply chain",
        "Procurement",
        "Sales",
        "CRM",
        "Marketing",
        "SEO",
        "Content strategy",
        "Customer success",
        # Soft skills
        "Communication",
        "Presentation",
        "Leadership",
        "Mentoring",
        "Problem solving",
        "Critical thinking",
        "Negotiation",
        "Time management",
        "Cross-functional collaboration",
        # Domain
        "Healthcare",
        "FinTech",
        "E-commerce",
        "SaaS",
        "B2B",
        "B2C",
        "Compliance",
        "GDPR",
        "SOC 2",
        "QA",
        "Manual testing",
        "Automation testing",
        "Selenium",
    }
)

JOB_ROLE_SUGGESTIONS = sorted(
    {
        "Software Engineer",
        "Senior Software Engineer",
        "Staff Engineer",
        "Frontend Developer",
        "Backend Developer",
        "Full Stack Developer",
        "Mobile Developer",
        "iOS Developer",
        "Android Developer",
        "DevOps Engineer",
        "Site Reliability Engineer",
        "Cloud Engineer",
        "Data Engineer",
        "Data Scientist",
        "Data Analyst",
        "Business Analyst",
        "Product Manager",
        "Technical Program Manager",
        "Project Manager",
        "Scrum Master",
        "UX Designer",
        "UI Designer",
        "Product Designer",
        "QA Engineer",
        "Security Engineer",
        "Machine Learning Engineer",
        "Solutions Architect",
        "Sales Engineer",
        "Customer Success Manager",
        "Account Executive",
        "Marketing Manager",
        "HR Generalist",
        "Recruiter",
        "Financial Analyst",
        "Accountant",
        "Operations Manager",
        "Supply Chain Analyst",
        "Nurse",
        "Physician",
        "Clinical Research Associate",
        "Mechanical Engineer",
        "Electrical Engineer",
        "Civil Engineer",
        "Attorney",
        "Paralegal",
        "Teacher",
        "Instructional Designer",
        "Administrative Assistant",
        "Executive Assistant",
    }
)
